// flow-typed signature: e7de961bff546a87024b9bb51f1e3e21
// flow-typed version: <<STUB>>/mastodon-api_v^1.0.2/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mastodon-api'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'mastodon-api' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mastodon-api/examples/authorization' {
  declare module.exports: any;
}

declare module 'mastodon-api/examples/home_timeline' {
  declare module.exports: any;
}

declare module 'mastodon-api/examples/streaming' {
  declare module.exports: any;
}

declare module 'mastodon-api/gulpfile.babel' {
  declare module.exports: any;
}

declare module 'mastodon-api/lib/helpers' {
  declare module.exports: any;
}

declare module 'mastodon-api/lib/mastodon' {
  declare module.exports: any;
}

declare module 'mastodon-api/lib/parser' {
  declare module.exports: any;
}

declare module 'mastodon-api/lib/settings' {
  declare module.exports: any;
}

declare module 'mastodon-api/lib/streaming-api-connection' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mastodon-api/examples/authorization.js' {
  declare module.exports: $Exports<'mastodon-api/examples/authorization'>;
}
declare module 'mastodon-api/examples/home_timeline.js' {
  declare module.exports: $Exports<'mastodon-api/examples/home_timeline'>;
}
declare module 'mastodon-api/examples/streaming.js' {
  declare module.exports: $Exports<'mastodon-api/examples/streaming'>;
}
declare module 'mastodon-api/gulpfile.babel.js' {
  declare module.exports: $Exports<'mastodon-api/gulpfile.babel'>;
}
declare module 'mastodon-api/lib/helpers.js' {
  declare module.exports: $Exports<'mastodon-api/lib/helpers'>;
}
declare module 'mastodon-api/lib/mastodon.js' {
  declare module.exports: $Exports<'mastodon-api/lib/mastodon'>;
}
declare module 'mastodon-api/lib/parser.js' {
  declare module.exports: $Exports<'mastodon-api/lib/parser'>;
}
declare module 'mastodon-api/lib/settings.js' {
  declare module.exports: $Exports<'mastodon-api/lib/settings'>;
}
declare module 'mastodon-api/lib/streaming-api-connection.js' {
  declare module.exports: $Exports<'mastodon-api/lib/streaming-api-connection'>;
}
