// flow-typed signature: c97113d481a2bb4f7b1d64ea432f17ac
// flow-typed version: <<STUB>>/react-icon_v^1.0.0/flow_v0.43.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-icon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-icon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-icon/lib/index' {
  declare module.exports: any;
}

declare module 'react-icon/src/index' {
  declare module.exports: any;
}

declare module 'react-icon/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-icon/lib/index.js' {
  declare module.exports: $Exports<'react-icon/lib/index'>;
}
declare module 'react-icon/src/index.js' {
  declare module.exports: $Exports<'react-icon/src/index'>;
}
declare module 'react-icon/test/index.js' {
  declare module.exports: $Exports<'react-icon/test/index'>;
}
